# Generated by Django 5.2.13 on 2026-04-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_servidor', models.CharField(max_length=50)),
                ('cpu', models.FloatField()),
                ('ram', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('es_anomalia', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Telemetrías',
            },
        ),
    ]
