# Generated by Django 5.2.13 on 2026-04-14 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetria',
            options={},
        ),
    ]
